config:
  ws_host_port: 1185
  webhost: '&6http://ip-client.craftmend.com//%username%'
chat:
  name:
    admin: '&3[&6OpenAudio-Admin&3]&7'
    normal: '&3[&6ImagineAudio&3]&7 '
  message:
    volume_set: '&6Volume set to&b %vol &6%'
    connected: '&bYou are now &2Connected&b to ImagineAudio!'
    connect: '&6 %client%'
    volume_error: '&4Nope, only numeric characters are accepted!'
