############################################################
# +------------------------------------------------------+ #
# |                      messages                        | #
# |      Messages that the player will see in chat       | #
# +------------------------------------------------------+ #
############################################################
messages:
  provide_url: '&2Click here to connect to our audio server!'
  connected: '&7You are now &2connected&7! yeey!'
  disconnected: '&7You are now &4disconnected7! cya next time!'





############################################################
# +------------------------------------------------------+ #
# |                      commands                        | #
# |       custom commands to give the user a link        | #
# +------------------------------------------------------+ #
############################################################
commands:
  audio: '/getlink'





############################################################
# +------------------------------------------------------+ #
# |                    web client                        | #
# |         Configuration for your web client!           | #
# +------------------------------------------------------+ #
############################################################
web:
  url: 'http://craftmend.com/lemmejusttestthismkay/lemmejusttestthismkay/'




############################################################
# +------------------------------------------------------+ #
# |                       data                           | #
# | Data that makes this server this server! (dont edit) | #
# +------------------------------------------------------+ #
############################################################
# key storage! NEVER SHERE THIS WITH ANYONE! NEVER CHANGE THIS DATA! (it wont work, trust me)
key:
  public: '-'
  private: '-'
