name: OpenAudioMc
version: 3.0
main: net.openaudiomc.jclient.OpenAudioMc
authors: [Mindgamesnl]
description: OpenAudiomc
website: https://openaudiomc.net/

commands:
  audio:
  connect:
  sound:
  oa:
  openaudio:
  openaudiomc:

permissions:
  oa.*:
    default: op
    description: A openaudio command
  oa.admin.*:
    default: op
    description: A openaudio command
  oa.admin.play:
    default: op
    description: A openaudio command
  oa.admin.stop:
    default: op
    description: A openaudio command